### ISSUE TITLE
Replace dates in the past with dates in the future

### ISSUE THREAD

**Issue by tsolakoua** [amadeus4dev/amadeus-code-examples#15]
This repository contains code examples for each API in several programming languages. The issue is that in a few examples the dates that are given as parameters are already in the past, such as [here](https://github.com/amadeus4dev/amadeus-code-examples/blob/8d6f371c65dd9e22761460890bf9c879dc853009/hotel_booking/v1/post/Node%20SDK/hotel_booking.js). 

The past dates in the API requests need to be updated with dates in the future (excluding of course APIs like Flight Most Booked and Flight Most Travelled Destinations that the input needs to be date in the past).

**Comment by biswain2309** [comment]
Hey! Can I take up this issue?

**Comment by tsolakoua** [comment]
Hello @biswain2309, I assigned the issue to you :) Once the contest starts you'll be able to make your PR, thank you very much!

**Comment by Mdreyazansari-0786** [comment]
sir i need some help to call my api in my booking website.
