### ISSUE TITLE
Flight analytics not showing after specific month

### ISSUE THREAD

**Issue by ankitoscar** [amadeus4dev/amadeus-code-examples#17]
Hey @tsolakoua, I am using the Amadeus API to create a flights data dashboard. I was using the [most booked flights](https://github.com/amadeus4dev/amadeus-code-examples/blob/master/flight_most_booked_destinations/v1/get/Python%20SDK/flight_most_booked_destinations.py) and [most travelled flights](https://github.com/amadeus4dev/amadeus-code-examples/blob/master/flight_most_traveled_destinations/v1/get/Python%20SDK/flight_most_traveled_destinations.py) functions, but they are not returning data after `2018-03`. Can you please look into it and tell me what is the problem here?

**Comment by ankitoscar** [comment]
I realised this is not the right place to open this issue, I think this should be done in [this repo](https://github.com/amadeus4dev/amadeus-python).

**Comment by tsolakoua** [comment]
In the test environment, the APIs return a subset of the production data. For more information check the test [data collection](https://github.com/amadeus4dev/data-collection).

**Comment by ankitoscar** [comment]
Cool, thanks for helping out 👍
