### ISSUE TITLE
No option to search only direct flights

### ISSUE THREAD

**Issue by aavetisyan24** [amadeus4dev/amadeus-code-examples#18]
Hi all,
Could you please help me to find out, how can I search only direct flights?

Thanks.

**Comment by tsolakoua** [comment]
Hello, you can use the parameter **nonStop**

```
GET https://test.api.amadeus.com/v2/shopping/flight-offers?originLocationCode=MAD&destinationLocationCode=ATH&departureDate=2022-06-12&adults=1&nonStop=true
```

**Comment by richburdon** [comment]
What is the POST alternative -- and is there a schema defined somewhere?

**Comment by tsolakoua** [comment]
The schema can be found in the [API reference](https://developers.amadeus.com/self-service/category/air/api-doc/flight-offers-search/api-reference), you can also check there a POST example
