### ISSUE TITLE
Unable to disable returnDate parameter in shopping.flight_offers_search.get. 

### ISSUE THREAD

**Issue by aavetisyan24** [amadeus4dev/amadeus-code-examples#19]
Hi, 
Here is my function for flight search. 
How I can disable day_return parametr ?  day_return=None , "null", "" ,  are not working. If there is value for day_return it's working. But what if there is no value, like say oneWay flight? 

____________________________
def flt_search(origin, destination, day_origin, **day_return=None**, stopover=None):

    try:
        response = amadeus.shopping.flight_offers_search.get(
            originLocationCode=origin,
            destinationLocationCode=destination,
            departureDate=day_origin,
            returnDate=day_return,
            adults=1,
            max=3,
            nonStop=stopover
        )
        message = response.data
        pprint.pprint(message)
        print(len(message))
        return message, origin, destination

    except ResponseError as error:
        return error

**Comment by tsolakoua** [comment]
When you are looking for flights with no return, you shouldn't pass the `returnDate` at all. Even if you try with `None` and `null` the backend still receives a `returnDate` with invalid inputs, since the expected input is in format `YYYY-MM-DD`.
