### ISSUE TITLE
Seats in FlightOfferPricing

### ISSUE THREAD

**Issue by bbwj122** [amadeus4dev/amadeus-code-examples#52]
Could you maybe provide an example to add a seat in FlightOfferPrice and FlightOffer.Booking.
We've added a seat in Additional Service in the FlightOfferPricing request following the YouTube video about it. We used a seatnumber that is available from the FlightOfferSearch result. Without errors about it, we don't see it in the result after the FlightOfferPricing result, nor in the FlightBooking result, which goes well and booking is made in Test Enviroment.
We're missing the seat adding in these code examples, unless we missed it somewhere.

**Comment by tsolakoua** [comment]
An example of how to add a seat can be checked [here](https://amadeus4dev.github.io/developer-guides/resources/flights/#select-a-seat)
