### ISSUE TITLE
I am using the Python SDK to search for Flight Fares, as per the code in the github. I am currently hitting the test url: test.api.amadeus.com.  However, when i compare the results, especially the fares returned by this API it is different from Google Flights. Of course I am keeping the parameters constant.

### ISSUE THREAD

**Issue by AshishKumarB** [amadeus4dev/amadeus-code-examples#54]
I am using the Python SDK to search for Flight Fares, as per the code in the github. I am currently hitting the test url: test.api.amadeus.com.  However, when i compare the results, especially the fares returned by this API it is different from Google Flights. Of course I am keeping the parameters constant.
try:
    response_eco = amadeus.shopping.flight_offers_search.get(
        originLocationCode='ATL',
        destinationLocationCode='CDG',
        departureDate='2023-03-08',
        adults=1,
        travelClass= 'ECONOMY', #'ECONOMY', 'PREMIUM_ECONOMY', 'BUSINESS', FIRST
        currencyCode='USD', nonStop= 'true')

**Comment by AshishKumarB** [comment]
@tsolakoua Is this because I am hitting a test url and when I move my app to PROD, i will get real-time data.

**Comment by tsolakoua** [comment]
I am not an expert with Google Flights, but maybe the offers you found could be coming from web scrapping the airline websites and the reasons why you see the different results could be the followings:
- Indeed in the test environment you don't get real-time data, you get cached ones.
- The Self-Service APIs return flights that airlines expose through the GDS. That means that the GDS content can be different from the one the airlines offer in their website directly or some negotiated offers OTAs might expose.
