### ISSUE TITLE
How can we get information about points or reward miles 

### ISSUE THREAD

**Issue by AshishKumarB** [amadeus4dev/amadeus-code-examples#58]
@tsolakoua  
I am currently use the Python SDK to call the amadeus.shopping._flight_offers_serach to get the fare in dollars for a given itinerary (departure and arrival IATA codes and dates). 
I was looking for your guidance to see if we can also get points or reward miles which are required to be redeemed for a given itinerary?

1. Can I tweak the existing API call to get points + cash 
2. do we have any separate API which gives award points or reward miles ?

Much appreciated your help in advance.

**Comment by tsolakoua** [comment]
Hello, this is not possible with the Self-Service APIs, however the functionality is available with the Enterprise APIs. If you want to know more [get in touch with the Enterprise team](https://developers.amadeus.com/support/contact-us-enterprise).
