### ISSUE TITLE
Regarding rooms available in a Hotel

### ISSUE THREAD

**Issue by bigmb** [amadeus4dev/amadeus-code-examples#60]
Hello,
I am using the python SDK and want to get the data of how many rooms are available in a hotel or the number of rooms already booked on a particular date. (I can even provide checkin -checkout date to check how many rooms are available.)
Not able to find this data in any response.

Thanks

**Comment by tsolakoua** [comment]
What you are looking for is not possible. The API returns the cheapeast room and if you want to search for additional rooms you can use the parameter `roomQuantity`.
