### ISSUE TITLE
Reg: Need ruby document for amadeus API's

### ISSUE THREAD

**Issue by shivareddy547** [amadeus4dev/amadeus-code-examples#62]
Hi Team,

I am looking for latest ruby supported examples, Can you please provide if we have any other repository or latest Gem?

Thanks in advance..!

Thanls
Shiva.A

**Comment by tsolakoua** [comment]
Hello, since the Amadeus Ruby SDK is not supported by the Amadeus for Developers team anymore as described [here](https://github.com/amadeus4dev-examples/amadeus-ruby), we don't add any more Ruby examples.
