### ISSUE TITLE
ERROR: trip-parser API returning 500 Internal Error

### ISSUE THREAD

**Issue by gregk8288** [amadeus4dev/amadeus-code-examples#65]
For the past few days the ```trip-parser``` api has been returning the following error. Any suggestions? Below is the example payload that we've been using including the response. 

**PAYLOAD**
`{
  "payload": "...",
  "metadata": {
    "documentType": "PDF",
    "name": "BOOKING_DOCUMENT",
    "encoding": "BASE_64"
  }
}`

**RESPONSE**
`{
    "errors": [
        {
            "code": 38189,
            "title": "Internal error",
            "detail": "An internal error occurred, please contact your administrator",
            "status": 500
        }
    ]
}`

If I look at the console, the error we.re getting is ```TypeError: Cannot read property 'id' of undefined```

**Comment by tsolakoua** [comment]
For API related questions get in touch with the [Amadeus for Developers support](https://developers.amadeus.com/support) team and make sure you provide the payload of the payload to be able to reproduce the case. Thanks!
