### ISSUE TITLE
flight_cheapest_date_search not working

### ISSUE THREAD

**Issue by BrianPfitz** [amadeus4dev/amadeus-code-examples#72]
Is this an outdated API endpoint or is it just not working on my site? I get the following error when I try to use curl:
`{'errors': [{'status': 500, 'code': 141, 'title': 'SYSTEM ERROR HAS OCCURRED', 'detail': 'ORIGIN AND DESTINATION NOT SUPPORTED'}]}`

**Comment by tsolakoua** [comment]
Usually this happens when the API doesn't have data for the specified origin and destination. 

For functional questions we suggest to contact the [support](https://developers.amadeus.com/support) of Amadeus for Developers Self-Service APIs.
